### PR TITLE
Remove box shadow clipping

### PR DESCRIPTION
**Pull request by altruisticsoftware**
Be free little cards

| Before | After |
| - | - |
| before | after |

### CODE REVIEW

**Comment by joshreisner** [comment]
thanks for the change -- the reason we have that `overflow="hidden"` is that if the content overflows it can enlarge the whole column

with
overflow-hidden

without
no-overflow

i'd love to merge this if we could find a solution, any ideas?

**Comment by altruisticsoftware** [comment]
Ah, that makes sense. Let me see if Chakra will accept the negative margin trick ⌛

**Comment by joshreisner** [comment]
hey i hope you don't mind, i pushed a change that i'm pretty sure would fix the issue. lmk if this works for you and i can merge it

**Comment by altruisticsoftware** [comment]
I dig it! Looks like IE11 and Safari don't though 🥲 
https://caniuse.com/mdn-css_properties_overflow-wrap_anywhere

Not sure what ya'll are targeting, but if that's not a showstopper then I'm down. Otherwise I can tinker with it a little more.

**Comment by joshreisner** [comment]
ooh thanks, good catch. i don't care about IE but i do want it to work properly on Safari. let's look at this some more and hopefully we'll figure it out

**Comment by joshreisner** [comment]
ok this looks pretty good, wdyt?

**Comment by altruisticsoftware** [comment]
womm, ship it 🚢

**Pull request merged**
